### ISSUE TITLE
Query for .go files

### ISSUE THREAD

**Issue by BrunoKrugel** [malbertzard/inline-fold.nvim#12]
How can I do a query to conceal the following code?

```
if err != nil {
...
}
```

**Comment by gh-liu** [comment]
> How can I do a query to conceal the following code?
> 
> ```
> if err != nil {
> ...
> }
> ```

[It doesn't work for multiline patterns.](https://github.com/malbertzard/inline-fold.nvim/blob/d0a24dd55c2fe9477e2636a589499fb7d530e9a3/README.md?plain=1#L5)
